create table if not exists public.rsvps (
  id bigint generated by default as identity primary key,
  full_name text not null,
  contact_number text not null,
  attendance text not null check (attendance in ('attending', 'declined')),
  attendee_count integer not null default 0 check (attendee_count >= 0),
  message text,
  created_at timestamptz not null default now()
);

alter table public.rsvps enable row level security;

create policy "Allow public RSVP submissions"
on public.rsvps
for insert
to anon
with check (true);
